### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by AngelaLuo49021** [hack4impact-uiuc/mentee#146]
#### Description
All the bugs we got

- [x] when editing profile, if a new school is added and then not filled out and then saved, returns isValid.includes is not a function
- [x] mentor profile linkedins and website dont actually link to them
- [x] remove mentor notification bell, and settings drop down
- [x] switch out bumblebee logo
- [x] remove home tab from mentor portal
- [x] add "focus on health" logo
- [x] uploading profile pic is now broken
- [ ] add some more space at the bottom of the profile page in the mentor portal
- [x] on mentor profile create, if you add an Education without filling in the fields, backend throws 422 instead of acting like there's no education at all
- [x] home page, say "all across the world" and 23+ speacializations
- [x] the first time is liek 3:0 instead of 3:00 for some reason??
![image](https://user-images.githubusercontent.com/42478474/104646750-80163200-5676-11eb-8fb0-16c2f16b8ec7.png)
- [ ] When changing mentor profile picture the top right doesn't update
![image](https://user-images.githubusercontent.com/28935000/104761644-d0e66300-5728-11eb-854d-45666550de04.png)
- [x] Appointments on Kelley's First Account. They aren't sorted correctly or atleast the first one isn't
- [x] Styling for overflowing text on appointments 
![image](https://user-images.githubusercontent.com/10874170/105406317-df81be00-5bf1-11eb-8da6-c4360bbcd801.png)

**Comment by chyku** [comment]
the one with top right profile picture doesn't update is complex imo idk how to access navbar state from edit profile
