### ISSUE TITLE
Mobile Friendly Mentor Video Page

### ISSUE THREAD

**Issue by Leundai** [hack4impact-uiuc/mentee#172]
#### Description
The Mentor Video page currently lacks support for mobile view

**Comment by chyku** [comment]
marking on hold because priority is mentee side mobile friendly

**Comment by robert-dm** [comment]
With the new layout this is ok 
<img width="408" alt="image" src="https://github.com/hack4impact-uiuc/mentee/assets/35821871/32d49c91-509a-4a74-be5e-e24f1808f385">
