### ISSUE TITLE
Change auth service to a react context

### ISSUE THREAD

**Issue by kenetec** [hack4impact-uiuc/mentee#199]
Let's move the authentication details (except the token) of a user from LocalStorage into memory by creating a [React Context](https://reactjs.org/docs/context.html) for the user data and [React Hooks](https://reactjs.org/docs/hooks-custom.html). This way, we can access any of those details from any React component.

**Comment by Bhargav252000** [comment]
Can I work on this issue ?
And can you please elaborate the details we to get from "registration" i.e email and passwords, right ?
