### ISSUE TITLE
Mobile Friendly Mentor Appointment Management

### ISSUE THREAD

**Issue by AngelaLuo49021** [hack4impact-uiuc/mentee#207]
#### Description
- make this mobile friendly
- get the nav bar fixes from andy's branch #205
- can ignore the calendar on the last page for now, that is an issue for later
![image](https://user-images.githubusercontent.com/42478474/108746229-aa72cf00-7501-11eb-892a-6c2d2196498b.png)

**Comment by robert-dm** [comment]
Already solved
<img width="429" alt="image" src="https://github.com/hack4impact-uiuc/mentee/assets/35821871/b3d2f049-0597-4d4e-8c29-ac7f0cb756b3">

<img width="478" alt="image" src="https://github.com/hack4impact-uiuc/mentee/assets/35821871/faa18575-2764-4127-bfd1-b8e0747c4704">
