### ISSUE TITLE
Admin Portal - Mentor Application Organizer

### ISSUE THREAD

**Issue by AngelaLuo49021** [hack4impact-uiuc/mentee#218]
#### Description
See figma for designs but check with Angela and Faith before starting

![image](https://user-images.githubusercontent.com/42478474/110004148-b9653880-7cdc-11eb-9477-09c7a0b03cc5.png)

**Comment by kenetec** [comment]
Feel free to use any library you want but here's one that looks pretty good: [react-beautiful-dnd](https://github.com/atlassian/react-beautiful-dnd/)
