### ISSUE TITLE
Gallery Card Styling Issues

### ISSUE THREAD

**Issue by chenfeiyu132** [hack4impact-uiuc/mentee#273]
**Describe the bug**

**To Reproduce**

1. Go to Find Mentors Page(Gallery)
2. Look at Gallery Cards

**Expected behavior**

**Screenshots**
<img width="1017" alt="Screen Shot 2021-04-05 at 6 48 26 PM" src="https://user-images.githubusercontent.com/21271918/113640132-a2916900-962f-11eb-96dc-b5dcf219e039.png">

<img width="1059" alt="Screen Shot 2021-04-05 at 6 55 01 PM" src="https://user-images.githubusercontent.com/21271918/113640163-b1781b80-962f-11eb-9253-64bc0fc41d91.png">

The current gallery cards differ quite a bit in terms of styling from the Figma designs, not sure if this is intentional

**Comment by AngelaLuo49021** [comment]
This def should not look like this. Reference the code on master to fix this because master looks fine
