### ISSUE TITLE
Profile Page CSS

### ISSUE THREAD

**Issue by Lam7150** [hack4impact-uiuc/mentee#433]
**Describe the bug**
Currently the profile page has a bunch of weird css issues and things are not displayed properly. Clean up the page and do the following:
1. Height does not reach bottom of screen
2. Not very responsive across screen sizes
3. Add professional title to the profile page (needs design consulting)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by AngelaLuo49021** [comment]
![image](https://user-images.githubusercontent.com/42478474/147141251-3fb84dcb-6336-4776-96c4-61ddf3d9687f.png)
some mentors have very long urls because it stems off of their company/university page

**Comment by AngelaLuo49021** [comment]
![image](https://user-images.githubusercontent.com/42478474/147141360-bd6aac48-ccb6-45fd-8fb1-ae65f7798bd5.png)
education gets cut off when the mentor is ultra-qualified
