### ISSUE TITLE
Fix Application Page CSS

### ISSUE THREAD

**Issue by Lam7150** [hack4impact-uiuc/mentee#435]
**Describe the bug**
Application page does not match figma mockups, make sure it matches it properly and is responsive on different browser sizes

**To Reproduce**
Figma mockups (admin portal): https://www.figma.com/file/9macEfYzayWu0k6ogNOUJA/Mentee-Mockup?node-id=1156%3A4249 

Current behavior:
![Screen Shot 2021-12-21 at 7 27 44 PM](https://user-images.githubusercontent.com/29765024/147014846-1664c220-45a4-441c-86a9-b9772e10e9d1.png)

Desired behavior: 
![Screen Shot 2021-12-21 at 7 27 34 PM](https://user-images.githubusercontent.com/29765024/147014841-a75e9a19-c50b-4449-9560-282131bc5d08.png)

**Expected behavior**

**Screenshots**

**Comment by shaund16** [comment]
@Lam7150 I can take care of this, I am having issues installing the packages on my system. Something about node sass
