### ISSUE TITLE
[apply-login-partner-changes] - Login as existing user Mentor and Mentee profiles

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#491]
**Describe the bug**
A previously existing user: leogalindofrias@gmail.com, had two profiles in application in dev database:  mentor and mentee, now I am unable to login with user as Mentor.  Mentee profile login works, Mentor profile login does not.

**To Reproduce**

1. Go to login page, enter leogalindofrias@gmail.com, pass123, click Mentee button
2. Login works, navigate page, click logout
3. Go to login page, enter leogalindofrias@gmail.com, pass123, click Mentor button
4. Error:  Nothing happens

**Expected behavior**
User should be able to login with any of both profiles, an user can have multiple roles
It was a previous working scenario.

**Screenshots**
NA

**Comment by eslamzaaki** [comment]
it works fine just make sure this email have 2 profiles from admin dashboard then try again @robert-dm

**Comment by robert-dm** [comment]
ok sure @eslamzaaki working
