### ISSUE TITLE
[apply-login-partner-changes] - Partner build profile page

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#492]
**Describe the bug**
Partner Build profile form not showing up, neither error message saying action to user

**To Reproduce**

1. Go to main page click APPLY
2. Enter any new email address
3. Click "Partner" radio button
4. Error:  neither a form is shown, neither a text saying what the problem is

**Expected behavior**
If user exists in database pre-created by Admin, then form must be shown with white background
If user does not exists in database, show all page orange with a text saying that email is not pre-registered as a Partner by an Admin.  So please contact administrator to create your user in the system before being able to Build profile 

**Screenshots**
![image](https://user-images.githubusercontent.com/35821871/165089932-fb308e7f-48a7-4781-a7f8-3cbf2e874502.png)

**Comment by eslamzaaki** [comment]
you need to preload email using admin @robert-dm

**Comment by robert-dm** [comment]
Not working @eslamzaaki please follow described steps and check expected behavior (2) still failing - we don't want the white space in the page if no form is shown, full page in orange must be, and user must receive a warning message at least.

**Expected behavior**
(1)**If user exists in database pre-created by Admin**, then form must be shown with white background
(2)**If user does not exists in database**, show all page orange with a text saying that email is not pre-registered as a Partner by an Admin. So please contact administrator to create your user in the system before being able to Build profile

**Comment by eslamzaaki** [comment]
fixed

**Comment by robert-dm** [comment]
ok working fine.
