### ISSUE TITLE
[apply-login-partner-changes] - Partner build profile form SDG fields should be checkboxes and not update Region field

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#494]
**Describe the bug**
Partner user trying to build profile, SDG list is not working as expected

**To Reproduce**

1. Go to landing page, select APPLY, enter email, select Partner (email must be pre-loaded by admin)
2. Complete form, when selecting Sustainable Development Goals Your Work Supports, it should be checkboxes to allow multiple selection
3. See error:  User selects only one value from SDG list (it can be many) but also another error is that value selected is reflected in Regions field instead

**Expected behavior**
SDG must be a list with checkboxes so that user can select multiple values and not affect other form fields.

**Screenshots**
![image](https://user-images.githubusercontent.com/35821871/165092120-a1b8286d-6c7e-495b-979e-3f2e8f87189b.png)

**Comment by eslamzaaki** [comment]
fixed @robert-dm

**Comment by robert-dm** [comment]
tested - ok @eslamzaaki
