### ISSUE TITLE
[apply-login-partner-changes] - Apply confirmation message layout

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#495]
**Describe the bug**
After applying, the application message should follow the design in Figma

**To Reproduce**

1. Go to APPLY
2. Click on Mentor radio button
3. Complete all fields
4. See confirmation message layout, is not same as of Figma.

**Expected behavior**
Same output as of Figma must be shown

**Screenshots**
**Current output**
![image](https://user-images.githubusercontent.com/35821871/165173087-9a5048d1-f58c-4ab3-809b-23c8fbcf9443.png)

**Expected output**
![image](https://user-images.githubusercontent.com/35821871/165173429-5292c3cb-5585-419b-a73a-cf33a0bd7907.png)

**Comment by eslamzaaki** [comment]
fixed

**Comment by robert-dm** [comment]
ok @eslamzaaki
