### ISSUE TITLE
[apply-login-partner-changes] - After build profile, the account verification step layout is broken at frontend

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#498]
**Describe the bug**
Not able to read the validation screen after build profile is created

**To Reproduce**

1. Go to build profile, complete form, Save
2. Click on Login
3. Complete username and password
4. See screen is not clear, layout is broken, not readable

**Expected behavior**
Screen should be clear to user

**Screenshots**
![image](https://user-images.githubusercontent.com/35821871/165176115-c20dad45-3cfb-47c4-8e92-213485cad76a.png)

**Comment by eslamzaaki** [comment]
fix UI @robert-dm

**Comment by robert-dm** [comment]
Fixed @eslamzaaki
