### ISSUE TITLE
[apply-login-partner-changes] - cannot create account Partner

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#501]
**Describe the bug**
Pre-loaded email cannot create account

**To Reproduce**

1. Go to main page, click apply, enter email robertmurer@gmail.com which was pre-loaded in admin as partner
2. Click on partner radio, then build profile button
**3. here there is first issue, build profile has to be clicked, but it should be automatic**
4. form will load to build partner profile
5. **here there will be another issue, form is pre-filled with test data**
6. make sure all fields are completed, click save
7. **here there is another issue, cannot save, see screenshot below**

**Expected behavior**
1) should be able to save if completed all fields
2) form should not be pre-filled when first load
3) build profile button should not be clicked manually

**Screenshots**
![image](https://user-images.githubusercontent.com/35821871/165207452-e8361048-7401-4a97-9b49-5f79768fd576.png)

![image](https://user-images.githubusercontent.com/35821871/165207478-aec1e7e6-3f4c-412e-9461-51269b6462f0.png)

**Comment by eslamzaaki** [comment]
fixed just take care to try with email doesn't have account in mentee and if you have account and don't have profile then password fields will be hidden and you can build profile as in firebase we can't make 2 accounts for same email so you need to use same password for multiple profiles @robert-dm

**Comment by robert-dm** [comment]
Before doing this test I have removed email from firebase as well from Mentee database, so I will do same  now @eslamzaaki
