### ISSUE TITLE
[apply-login-partner-changes] - Mentor apply form, how you identify question, options

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#503]
**Describe the bug**
wrong radiobutton option name "oman" should be "woman"

**To Reproduce**

1. Go to apply complete email apply as mentor
2. Complete the form
3. review question how you identify, answer oman is there, it should be woman

**Expected behavior**
woman instead of oman

**Screenshots**
![image](https://user-images.githubusercontent.com/35821871/165932542-373fb570-afaf-4aa4-9a7f-e02d361bb92d.png)

**Comment by eslamzaaki** [comment]
fixed

**Comment by robert-dm** [comment]
ok fixed
