### ISSUE TITLE
[apply-login-partner-changes] - Login as Partner, Find a mentee option should not be there

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#504]
**Describe the bug**
After an user login as Partner, in header no option to Find a Mentee should appear.  Only option should be Find a Partner, Gallery result should display other Partners

**To Reproduce**

1. Go to Login, and complete login as a Partner
2. In header there is a button Find a Mentee, it should be replaced with Find a Partner
3. Partners can only find other partners to message among them

**Expected behavior**
Partners can only find other partners to message among them

**Screenshots**

![image](https://user-images.githubusercontent.com/35821871/165935452-32e290c7-32c3-478d-b5b7-b6f509d8c343.png)

![image](https://user-images.githubusercontent.com/35821871/165935498-f767d225-70ca-4f00-91e2-02aaf0713dfa.png)

**Comment by eslamzaaki** [comment]
partner dashboard not developed yet this just prepreation for stage3

**Comment by robert-dm** [comment]
@eslamzaaki issue still there no message button is shown.

**Comment by robert-dm** [comment]
closing it @eslamzaaki
