### ISSUE TITLE
[apply-login-partner-changes] - admin dashboard view issue in left menu - dev environment

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#508]
**Describe the bug**
In https://mentee-dev.herokuapp.com/admin/ dev environment, the left menu layout looks ugly and broken, see screenshot.

**To Reproduce**

1. Go to https://mentee-dev.herokuapp.com/admin/ 
2. Login as klhester3@gmail.com / pass123
3. Look left menu, it looks broken layout

**Expected behavior**
Left menu should not look like that.

**Screenshots**
![image](https://user-images.githubusercontent.com/35821871/166129405-0551c555-b122-4398-a704-2a8fa06f495c.png)

**Comment by eslamzaaki** [comment]
fixed @robert-dm

**Comment by robert-dm** [comment]
fixed
