### ISSUE TITLE
[apply-login-partner-changes] - Save button at the bottom in application page

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#509]
**Describe the bug**
On the application page could we place the Save button at the bottom

**To Reproduce**

1. Go to build profile
2. complete the form
3. Save button remains on top.  Let-s move to the bottom

**Expected behavior**
On the application page could we place the Save button at the bottom

**Comment by robert-dm** [comment]
@eslamzaaki this issue still pending.

**Comment by eslamzaaki** [comment]
@robert-dm  fixed

**Comment by robert-dm** [comment]
right, thanks.
