### ISSUE TITLE
[apply-login-partner-changes] - admin login, put a button login just below password

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#511]
**Describe the bug**
In the admin login, page cannot be scrolled down, so please add button to Login

**Comment by eslamzaaki** [comment]
fixed @robert-dm

**Comment by robert-dm** [comment]
tested locally, couldn't merge code, Login button is not showing up.

**Comment by eslamzaaki** [comment]
I can't figure out where is problem you talk about /admin ?
because it is scrollable and admin login button exist in all screen sizes @robert-dm

**Comment by robert-dm** [comment]
Ok if it is scrollable we can close it, thanks.
