### ISSUE TITLE
[apply-login-partner-changes] - Partner created but no confirmation appears.

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#513]
**Describe the bug**
Partner, after complete build profile form, then save, no confirmation message appears, user is redirected to APPLY - LOGIN page, we need to show at least an alert that profile was created and now can login.

And no welcome email is sent to user also.

**To Reproduce**

1. Go to admin, create an user as Partner, logout
2. Click on APPLY, enter email added by admin, click Partner button
3. Complete form, save
4. See error: no confirmation message, no email, just a redirect to login

**Expected behavior**
Confirmation message that profile was successfully created.   Email delivered to user that is welcome to mentee.

**Comment by eslamzaaki** [comment]
@robert-dm  added message and email

**Comment by robert-dm** [comment]
fixed
