### ISSUE TITLE
[apply-login-partner-changes] - View Profile not showing up for all Partners

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#514]
**Describe the bug**
Can't click View profile button in the bottom Partners, scroll is not scrolling more than that

**To Reproduce**

1. Find Partner, see bottom list, can't see View Profile button even reducing zoom

**Expected behavior**
All partners can be viewed in profiles.

**Screenshots**
![image](https://user-images.githubusercontent.com/35821871/167302512-f5105e2d-93ed-49f8-a271-33f5269d1803.png)

**Comment by eslamzaaki** [comment]
@robert-dm  fixed

**Comment by robert-dm** [comment]
fixed 
![image](https://user-images.githubusercontent.com/35821871/167497661-7b2a79bf-b8df-471e-ba3a-08ccd266b49b.png)
