### ISSUE TITLE
[apply-login-partner-changes] - Message button not shown in Partners

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#515]
**Describe the bug**
I cannot message other partners, no button to message them

**To Reproduce**
Find other partners, no message button

**Expected behavior**
Message button must be shown next to View Profile button so that I can message and chat with other partners.

**Screenshots**
![image](https://user-images.githubusercontent.com/35821871/167302681-0129c344-16de-44d8-a63c-880a94bc950e.png)

**Comment by eslamzaaki** [comment]
threre was no bug you have to profile to message him this default behaviour @robert-dm

**Comment by robert-dm** [comment]
correct @eslamzaaki
