### ISSUE TITLE
[apply-login-partner-changes] - Partner filter to search other partners

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#517]
**Describe the bug**
When a Partner logs in, and finds other partners, filter must show other options 

**Sustainable Development Goals Your Work Supports *** -- user select checkboxes with auto refhresh like regions
**Current & Upcoming Project Topics** * -- user type and search automatically like "search by name"
**Organization/Institution/Corporation Full Name ***  -- user type and search automatically like "search by name"

**Comment by eslamzaaki** [comment]
@robert-dm  done

**Comment by robert-dm** [comment]
thanks @eslamzaaki
