### ISSUE TITLE
[apply-login-partner-changes] - Training page layout

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#520]
**Describe the bug**
Training page layout is not following page design, please make below adjustements to improve it

1- Make sure button confirm training is not over any video or document, see screenshot
2 - Can we make videos a little bit bigger?
3- Not sure if white background looks good, maybe all Orange?  Can we try?

**Screenshots**
![image](https://user-images.githubusercontent.com/35821871/167522022-0aa7fb21-160a-495a-b2ce-e9a83826490e.png)

**Comment by eslamzaaki** [comment]
@robert-dm  done

**Comment by robert-dm** [comment]
ok
