### ISSUE TITLE
[apply-login-partner-changes] - left menú missing for partner user after account verification first login

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#523]
**Describe the bug**
After account verification is completed, user is redirected to a page that has no left side menu, see screenshots below

1.create partner account, build profile, confirm email after login

**Screenshots**
![image](https://user-images.githubusercontent.com/35821871/167625809-42e9a2ba-75fc-4c4f-b1bf-99054905f42a.png)

![image](https://user-images.githubusercontent.com/35821871/167643156-cfe8acf4-018b-4962-8dec-2ea73ee3b37f.png)

**Comment by eslamzaaki** [comment]
@robert-dm  FIXED

**Comment by robert-dm** [comment]
working fine
