### ISSUE TITLE
[apply-login-partner-changes] - Mentor Calendar Availability and previous calendar events completed, upcoming not shown

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#525]
**Describe the bug**
Mentor users not able to see calendar to setup availability, and not able to see past events in calendar

**To Reproduce**

1. Go to login, enter leogalindofrias@gmail.com / pass123
2. Click on Mentor button
3. Go to main portal view, click Availability
4. See error calendar is greyed out

**Expected behavior**
User must be able to setup the calendar availability, this is an existing feature
User must be albe to see past events and upcoming events too.

**Screenshots**
![image](https://user-images.githubusercontent.com/35821871/168118001-eb23ecb2-9ad7-45d3-b796-5907bea83565.png)

**Comment by eslamzaaki** [comment]
@robert-dm  done

**Comment by robert-dm** [comment]
ok
