### ISSUE TITLE
New feature for notification Admin when new Mentor is completed

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#541]
User Story:
As administrator user, I want to see a notification in the bell (right side upper corner) when a new mentor completed the application build profile, so that I am aware of new Mentor's, I can click the mentor user name from the bell, then share that out with mentees to highlight them as new. 

Current limitation:  As it is I as Admin, don’t know when someone has completed everything

Acceptance Criteria:
- Notification at bell in Admin screen whenever a new Mentor user finishes application
- Admin user able to click that Mentor user name
- Admin user able to see the Mentor profile details.

Additional information:
Requirement in User words:
Could we add a notification to the admin portal when a global mentor has completed their BUILD process and now are in the gallery? A notification that appears as a bell like the other notifications and when I click show me their name or is linked to their profile?

**Comment by eslamzaaki** [comment]
Done
