### ISSUE TITLE
Mentee!  Add date and time on every chat message in frontend

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#552]
For all the messages in chat functionality, display in frontend the date and time each message was sent.

**Comment by eslamzaaki** [comment]
![task-messages](https://user-images.githubusercontent.com/44367509/189508840-8011b024-c0d6-401f-a246-c0be241ba145.png)

**Comment by robert-dm** [comment]
Data and time not showing up after merge
![image](https://user-images.githubusercontent.com/35821871/189540839-b02e55f3-fff0-4aa3-b4c6-7941820a9e83.png)
