### ISSUE TITLE
Mentor profiles not having calendar enabled, are al disabled

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#553]
**Describe the bug**
When a Mentor user logs into the platform, goes to Availability and the calendar is disabled

**To Reproduce**

1. Log in as Mentor user, Go to appointments, Availability
2. The calendar is disbled

**Expected behavior**
The calendar should be enabled for all Mentor users to setup the availability

**Screenshots**
<img width="1640" alt="image" src="https://user-images.githubusercontent.com/35821871/189485522-65413154-5120-412c-b972-e116ff3f850a.png">

**Comment by eslamzaaki** [comment]
![task-ava-1](https://user-images.githubusercontent.com/44367509/189508802-04510830-b400-467b-99e9-17597546be67.png)
![task-ava-2](https://user-images.githubusercontent.com/44367509/189508805-2254c5be-4200-48cf-8342-988f3fb867de.png)

**Comment by robert-dm** [comment]
ok
