### ISSUE TITLE
Issues in layout after library upgrade

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#602]
Messages left bar has black background, style was changed
<img width="1715" alt="image" src="https://user-images.githubusercontent.com/35821871/223567468-03c8a04e-fd7a-4780-8861-88f56a4371a6.png">

**Comment by SolMon9099** [comment]
It is related to upgrade of ant.
I added style for white background to message sidebar

**Comment by robert-dm** [comment]
solved
