### ISSUE TITLE
Restrict GET all mentors request

### ISSUE THREAD

**Issue by chyku** [hack4impact-uiuc/mentee#64]
#### Description
A lot of data leaks can happen from you looking at the network tabs on inspect element, where you can see exactly what data is returned from a request. We want to prevent unnecessary mentor data leakage by [only retrieving the subset of fields that are necessary](https://docs.mongoengine.org/guide/querying.html#retrieving-a-subset-of-fields).

The fields you should hide are any fields that aren't displayed on the mentee-facing [mentor gallery](https://www.figma.com/file/9macEfYzayWu0k6ogNOUJA/Mentee-Draft-1?node-id=250%3A0).

#### Files
`backend/.../views/main.py`

#### Tasks
- [ ] #815
- [ ] Hide them in code
- [ ] Test and screenshot

**Comment by Leundai** [comment]
![image](https://user-images.githubusercontent.com/28935000/97375739-8e2f9000-1889-11eb-987b-bca58c06645e.png)

**Comment by SolMon9099** [comment]
- Figure out what fields you need to hide
      firebase_uid
      linkedin
     website
     education
     biography
     taking_appointments
     text_notifications
     email_notifications
     email
     videos
     availability

 - Hide them in code
    I have changed the api code to get Mentor data, hide above fields.
    https://mentee-dev.herokuapp.com/gallery
![image](https://github.com/hack4impact-uiuc/mentee/assets/101564382/db1e0751-7826-4716-907f-1e2693258bb1)

 - Test and screenshot
     Before
![image](https://github.com/hack4impact-uiuc/mentee/assets/101564382/43b9a2f3-0e1e-4ff8-9083-300e53d8d991)

     After
![image](https://github.com/hack4impact-uiuc/mentee/assets/101564382/ac3421fd-5c4d-4db9-812f-1994c8682f5a)
