### ISSUE TITLE
Handle Sendgrid 100 email per day preventing sending messages

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#659]
1. Login as Mentee user, i.e. robertmurer+mentee1@gmail.com - password123
2. Find a Mentor, View Profile of any mentor who has not been contacted earlier.  I.e. find this mentor robertmurer+mentor5@gmail.com.  Click View Profile button
3. Click Contact Me
4. Select areas of interest
5. Click option Email
6. Enter introduction message
7. Click submit 
Error, nothing happens, message is not submitted.

seems error is 
Go {message: 'Request failed with status code 500', name: 'AxiosError', code: 'ERR_BAD_RESPONSE', config: {…}, request: XMLHttpRequest, …}

<img width="1688" alt="image" src="https://user-images.githubusercontent.com/35821871/225785244-9b7e179d-2db0-449d-9e93-19fd1129ef54.png">

**Comment by robert-dm** [comment]
Issue in prod from user

https://user-images.githubusercontent.com/35821871/225785421-0e581146-eb72-4c59-a555-c45c72df65ef.MOV

**Comment by Leundai** [comment]
Synced offlined: This issue is caused by Sendgrid's 100-email daily limit. The proposal is to swap flow so that appointments are still booked.
