### ISSUE TITLE
Fix Admin Notifications CSS

### ISSUE THREAD

**Issue by Leundai** [hack4impact-uiuc/mentee#678]
#### Description
Its really whack

#### Screenshots
<img width="362" alt="Screen Shot 2023-03-22 at 8 43 29 PM" src="https://user-images.githubusercontent.com/28935000/227086721-2f4b145b-6df5-42dd-9d29-8732b37b545b.png">

#### Files
`Navheader.js:257`

**Comment by robert-dm** [comment]
This was removed in the new UI.

<img width="1512" alt="image" src="https://github.com/hack4impact-uiuc/mentee/assets/35821871/21b1e464-f92b-4993-a1d8-93858af275dd">
