### ISSUE TITLE
Missing translation the menu item Explore

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#764]
<img width="1712" alt="Screenshot 2023-07-31 at 22 20 41" src="https://github.com/hack4impact-uiuc/mentee/assets/35821871/91382726-aaa5-4ffd-9c42-f92c5598b017">

**Comment by Leundai** [comment]
This missing translation is accounted for in `en-US/translations.json` , however, we still need to add these to the spreadsheet...

We will create a separate PR for this

**Comment by robert-dm** [comment]
this is resolved
