### ISSUE TITLE
Impersonation feature

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#784]
As an support user I need to impersonate other user profiles so that I can analyze bugs and issues.

Features 

- [ ] admin user able to create / disable / remove support users
- [ ] support users can have same email as other users in the platform
- [ ] support users will be allowed to login, using /support url context
- [ ] there is no need to add a new Support role option in the login screen
- [ ] support users will be able to click in the top right image icon, and select impersonate user, select the role to impersonate (mentee, mentor, partner, admin) and then select the users that belongs to that role
- [ ] support user will be able to see the platform as if it were the selected user logged in
- [ ] once the user has been switched with impersonation, support user can go back to the support view, as well as change to another role-user
- [ ] support user will see a header as a sticky banner, showing a message saying that the session is being impersonated as user xxxxxx (selected user) and role xxxx (selected role)

**Comment by robert-dm** [comment]
@SolMon9099 testing, I have created a support user, not able to login
<img width="1054" alt="image" src="https://github.com/hack4impact-uiuc/mentee/assets/35821871/70621f27-1662-42a0-a5a7-af23fd6a8773">

**Comment by robert-dm** [comment]
@SolMon9099 an existing email associated with other roles, can be created as support too.

<img width="995" alt="image" src="https://github.com/hack4impact-uiuc/mentee/assets/35821871/caf66a10-4e33-4b66-81a5-15ebc4863f8b">

**Comment by robert-dm** [comment]
@SolMon9099 when adding a support user as admin, it is being added as Guest.

**Comment by SolMon9099** [comment]
I fixed this error
