### ISSUE TITLE
Events, when being created an error is shown, and no image is uploaded to Event

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#788]
After event was created an error was shown, event appears in system but the image uploaded is missing.

Pls fix the error message should not be there and Image must be uploaded, and cropped horizontally to fit the gallery object.

![image](https://github.com/hack4impact-uiuc/mentee/assets/35821871/5957af48-c318-49f1-aacd-f83f5521aa24)

**Comment by SolMon9099** [comment]
I have fixed this issue. Added loading while save new event or delete event.

**Comment by robert-dm** [comment]
Solved
