### ISSUE TITLE
Style used in Dates is not correct, not following the website UI

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#791]
Please follow the style, the dates are shown in blue color, it is not part of the style

<img width="1451" alt="image" src="https://github.com/hack4impact-uiuc/mentee/assets/35821871/151bcf97-083f-4524-9712-b5aa5e349b63">

Instead, for dates please use this style
<img width="108" alt="image" src="https://github.com/hack4impact-uiuc/mentee/assets/35821871/cbb7431b-0584-424c-bca3-5a6a62650af2">

**Comment by SolMon9099** [comment]
I changed the color of dates

**Comment by robert-dm** [comment]
solved
