### ISSUE TITLE
Events - Images to be shown horizontally

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#792]
Image must be shown horizontally, pls add a crop option when adding an image to fit this space

<img width="1493" alt="image" src="https://github.com/hack4impact-uiuc/mentee/assets/35821871/64e9197e-d13c-4a04-9f05-f07cb4a5fbee">

**Comment by SolMon9099** [comment]
I added crop feature when add image

**Comment by robert-dm** [comment]
@SolMon9099 crop feature is fine but UI in card is not looking good, very ugly.  Can we fix it by expanding horizontally? the width must be adjusted. 

<img width="959" alt="image" src="https://github.com/hack4impact-uiuc/mentee/assets/35821871/9d92e9e0-36aa-4e57-945f-873b5f3ca0e1">
