### ISSUE TITLE
Events, add More Details button and extend Summary text

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#793]
In the events, please add a View Details button, onClick it must open the Event to see the whole details in a bigger option
This should apply to all roles

Also in the Gallery view, extend the text in the Summary.

<img width="1539" alt="image" src="https://github.com/hack4impact-uiuc/mentee/assets/35821871/718990e8-bbad-4434-b7c6-0a1c82403b0b">

**Comment by SolMon9099** [comment]
If mouse over on summary area, the whole summary text is displayed on hover popup.
And then on edit event modal, you can also see whole summary. Is it necessary to add more detail button?
![image](https://github.com/hack4impact-uiuc/mentee/assets/101564382/26316b23-0e21-4a28-be16-e78e5a2ba993)

**Comment by robert-dm** [comment]
@SolMon9099 the View Event button requested is not shown

**Comment by robert-dm** [comment]
@SolMon9099 yes it is necessary to add View Event button.
