### ISSUE TITLE
Events - All Day option is removing the Start Date //  No End Date option, remove it

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#794]
The All Date option is not allowing to select the Event initial date

<img width="1663" alt="image" src="https://github.com/hack4impact-uiuc/mentee/assets/35821871/0618bfc7-7a95-4303-b2bb-ef8bdd3b1d4a">

also remove the No End Date option, it is not needed.

**Comment by SolMon9099** [comment]
I removed All day and no end date options

**Comment by robert-dm** [comment]
removed
