### ISSUE TITLE
Events - Partner user not able to see the Events page

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#795]
As a partner user, not able to see Events page

logged in as user robertmurer+partner1@gmail.com / password123

<img width="1723" alt="image" src="https://github.com/hack4impact-uiuc/mentee/assets/35821871/8757adf0-f369-4917-87b1-1ebc7fc8dfb4">

**Comment by SolMon9099** [comment]
I have fixed this issue

**Comment by robert-dm** [comment]
closed
