### ISSUE TITLE
Events - as an Admin, when adding Event, not able to select for which role it is

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#796]
As an admin, when adding Event, it is being added for all the roles?  Admin should be able to indicate for which role it is.

<img width="1671" alt="image" src="https://github.com/hack4impact-uiuc/mentee/assets/35821871/5181b9b7-20a1-4bc8-b3f7-40aa8b7ab5c7">

**Comment by SolMon9099** [comment]
I added the feature for assign role when admin user add/edit event.

**Comment by robert-dm** [comment]
solved
