### ISSUE TITLE
Model for asynchronous mentoring videos

### ISSUE THREAD

**Issue by chyku** [hack4impact-uiuc/mentee#8]
#### Description
As listed on the doc, create a model for a mentor's uploaded videos. It should look like:

> Links to videos for asynchronous mentoring:
> - ListField of Object with link (StringField) + tag (StringField)

Include constructor (`__init__`) and `__repr__` functions

#### Files
`backend/api/models/[namehere].py`

#### Tasks
- [ ] Create the model!

**Comment by Leundai** [comment]
Lmk if I should add anything else for the __repr__ or if I am missing something important. 😃

**Comment by Leundai** [comment]
@chyku Should for the tags how should go about storing them or just a Stringfield? It might be that the same tags will be used a lot in multiple videos too.
