### ISSUE TITLE
Add a new field in the Application form, to select the Partner.

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#904]
add a field in the Application form, so that the Mentee, or Mentor, can select the Partner mandatory.

Field label "If you are currently affiliated to a partner organization, please select it from the below list, or select no-affiliation." 

- New field must be in Mentee Application form 
- It should list all the Partners from the system to be selected, plus one more option "no-affiliation"
- New field must be mandatory
- The field label should be translated to all existing languages
- if mentee user selected a partner, the partner will be shown to the user in the gallery (existing feature)
- if mentee user selected a partner, the partner will show the mentte user associated to partner, in the admin dashboard (existing)
- admin can remove the mentee from the partner at any time.

**Comment by robert-dm** [comment]
@SolMon9099 

please add no-affiliation as last value in the dropdown
please translate no-affiliation if possible to all languages

<img width="1210" alt="image" src="https://github.com/hack4impact-uiuc/mentee/assets/35821871/322c94a2-6b5b-4384-b85f-eb02585fb6fe">

**Comment by SolMon9099** [comment]
I changed the other
