### ISSUE TITLE
Willing to fix the cypress and backend test

### ISSUE THREAD

**Issue by sharibislam** [hack4impact-uiuc/mentee#930]
Team, 

I am willing to fix the cypress and backed test, But i need some help in order to setup project in my local machine.

I have run docker-compose up command but it's failing due to missing config file.

**Comment by robert-dm** [comment]
Hi @sharibislam pls let me know who contacted you to work on this?

**Comment by sharibislam** [comment]
Hi @robert-dm , I saw one post on Upwork and i would like volunteer to this project.
