### ISSUE TITLE
Partner - Profile page not loading after login.

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#951]
Profile page not loading for a Partner

![image](https://github.com/hack4impact-uiuc/mentee/assets/35821871/07554b57-0cf7-4d81-837f-5b999fc56d70)

**Comment by SolMon9099** [comment]
This is related to partner user data on dev. There are only 3 partner profiles on dev now

**Comment by robert-dm** [comment]
I cannot create a partner profile again for user robertmurer+partner1@gmail

<img width="1466" alt="image" src="https://github.com/hack4impact-uiuc/mentee/assets/35821871/5439f555-d101-412c-b95b-be2407ebb93d">
