### ISSUE TITLE
Events issues for Mentor in Events page

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#953]
Step to Reproduce:
Go to URL http://localhost:3000/login
Click on Mentor
Type email i.e. [robertmurer+mentor1@gmail.com](mailto:robertmurer+mentor1@gmail.com)
Type password i.e. password123
Click on Submit button
Click on Events menu

https://github.com/hack4impact-uiuc/mentee/assets/35821871/f7f0c4bb-282c-4048-87be-eb94162ad572

**Comment by robert-dm** [comment]
Hi @Humayun0008 could you please explain how do you arrive to this error?  We have tried in https://mentee-dev.herokuapp.com/events with same credentials but no error is shown.  How do you get that popup ?

**Comment by robert-dm** [comment]
@Humayun0008 have you tried in the dev url?

**Comment by Humayun0008** [comment]
> @Humayun0008 have you tried in the dev url?

No, I don't tried on dev URL (https://mentee-dev.herokuapp.com/events)

**Comment by robert-dm** [comment]
Please try in dev URL and confirm this issue persist or not. @Humayun0008

**Comment by Humayun0008** [comment]
Working as Expected
