### ISSUE TITLE
AdminFindPartnerTest - Test Filter By Project Topics Issue

### ISSUE THREAD

**Issue by Humayun0008** [hack4impact-uiuc/mentee#956]
**Describe the bug**
Unable to search the Project Topics

**To Reproduce**

1. Go to 'http://localhost:3000//admin' or 'https://mentee-dev.herokuapp.com/admin'
2. Type the Username and Password
3. Click on 'Login' Button
4. Scroll down to 'Find a Partner' Menu and Click on That menu
5. In 'Project Topics' Search Field Type 'partner' 
6. See error

**Expected behavior**
Result should be shown according to the search 

**Screenshots**
Please find the attached screenshots and Video
![Error](https://github.com/hack4impact-uiuc/mentee/assets/131605337/73bd74d1-911e-47ca-9c6b-370663c5c370)
![error2](https://github.com/hack4impact-uiuc/mentee/assets/131605337/ca91af5d-d9a1-40b5-9b10-eca8c7bad270)

https://github.com/hack4impact-uiuc/mentee/assets/131605337/3b2f1e43-e50c-49d0-881e-2e07118c45ea

**Comment by robert-dm** [comment]
Hi @SolMon9099 could you please fix this issue?  This may have been broken with any change done lastly.

**Comment by Humayun0008** [comment]
Retested-----Working as Expected
