### ISSUE TITLE
Guest user cannot Find a Partner

### ISSUE THREAD

**Issue by robert-dm** [hack4impact-uiuc/mentee#959]
Testcase #1 Find Partner
Go to the URL https://mentee-dev.herokuapp.com
Click on Guest
Enter email [robert+guest@menteeglobal.org](mailto:robert+guest@menteeglobal.org)
Enter Password “password123”
Click on “Find a Partner”
Actual Result: API error is shown
Expected Result: User should be able to Find a partner

![image](https://github.com/hack4impact-uiuc/mentee/assets/35821871/a8c70eb8-4a85-441f-acd8-4a42ff3f8baa)

**Comment by robert-dm** [comment]
@Humayun0008 this bug is fixed, in dev,  could you please uncomment the test script
[robert+guest@menteeglobal.org](mailto:robert+guest@menteeglobal.org)

**Comment by Humayun0008** [comment]
Issue Resolved ....  Working as Expected
